'use client';

import Link from 'next/link';
import { ArrowUpRight, Check, Plus } from 'lucide-react';
import SiteFooter from '@/components/layout/SiteFooter';
import { PublicHeader } from '@/components/public/PublicBrand';
import { useAuthStore } from '@/stores/auth';

const sections = [
  { id: 'profile', number: '01', title: '병원 소개를 연결하세요.', sub: 'START WITH YOUR CLINIC', text: 'Patient Hub에 등록된 병원 정보를 가져오거나 직접 입력하세요. 지역과 주력 진료, 병원의 특징을 구체적으로 적으면 관련 있는 핵심 질문을 추천받을 수 있습니다.', points: ['Hub에서 가져온 소개도 시그널에서 수정할 수 있습니다.', '설정에서 병원 정보와 소개를 다시 확인할 수 있습니다.'], href: '/dashboard/settings', link: '병원 설정 열기' },
  { id: 'questions', number: '02', title: '우리 병원에 중요한 질문을 고르세요.', sub: 'ASK WHAT MATTERS', text: '추천 질문을 살펴보고 실제 환자분이 궁금해할 내용으로 수정하세요. 진료, 지역, 비교 기준 등 질문의 의도가 분명할수록 결과를 이해하기 쉽습니다.', points: ['핵심 질문을 검토한 뒤 추가하거나 기존 질문을 교체합니다.', '같은 질문이 이미 등록되어 있으면 해당 질문의 답변을 열 수 있습니다.'], href: '/dashboard/prompts', link: '질문 관리 열기' },
  { id: 'answers', number: '03', title: '점수와 함께 실제 답변을 보세요.', sub: 'READ THE EVIDENCE', text: '질문에서 답변 보기를 열면 측정된 AI 응답 원문을 확인할 수 있습니다. 플랫폼과 측정일을 살피고, 어떤 맥락에서 병원이 언급됐는지 읽어보세요.', points: ['측정된 답변이 아직 없으면 결과가 수집된 뒤 확인할 수 있습니다.', '질문을 교체해도 이전 질문과 그 답변은 보관됩니다.'], href: '/dashboard/prompts', link: '질문별 답변 열기' },
  { id: 'competitors', number: '04', title: '경쟁 병원 사이의 위치를 확인하세요.', sub: 'KNOW YOUR POSITION', text: '비교하고 싶은 경쟁 병원을 직접 추가하세요. 같은 기간에 수집된 AI 답변에서 각 병원이 등장한 비율로 등록 병원 간 순위를 보여줍니다.', points: ['경쟁 병원 한도는 S 3개, M 10개, L 20개입니다.', '순위는 진료의 질을 평가하지 않으며, 비교 대상으로 등록한 병원에 한정됩니다.', '측정 자료가 없거나 표본이 적으면 화면에 상태를 표시합니다.'], href: '/dashboard/competitors', link: '경쟁 병원 비교 열기' },
  { id: 'track', number: '05', title: '변화를 꾸준히 관찰하세요.', sub: 'FOLLOW YOUR SIGNAL', text: '대시보드에서 점수와 플랫폼별 흐름을 확인하고, 변화가 생긴 질문의 답변을 살펴보세요. AI 응답은 질문과 측정 시점에 따라 달라질 수 있습니다.', points: ['정기 측정은 FREE 주 1회, S 주 2회, M·L 매일입니다.', '지원 플랫폼과 라이브 쿼리 횟수는 요금제에서 확인할 수 있습니다.'], href: '/dashboard', link: '대시보드 열기' },
];

export default function GuidePage() {
  const { isAuthenticated, _hasHydrated } = useAuthStore();
  const loggedIn = _hasHydrated && isAuthenticated;
  return <div className="min-h-screen bg-[#f1f1eb] text-[#141512]"><PublicHeader active="guide" loggedIn={loggedIn} /><main className="mx-auto max-w-[1440px] px-5 sm:px-10 lg:px-14">
    <section className="border-b border-[#141512] py-14 lg:py-20"><p className="mb-6 text-[11px] font-semibold tracking-[0.18em] text-[#72756a]">THE SIGNAL FIELD GUIDE</p><div className="grid gap-6 lg:grid-cols-[1.2fr_0.8fr] lg:items-end"><h1 className="text-5xl font-semibold leading-[1.15] tracking-[-0.065em] sm:text-6xl lg:text-7xl">처음부터,<br />차근차근.</h1><p className="max-w-sm text-sm leading-7 text-[#687253]">병원 소개를 연결하는 순간부터<br />질문과 답변, 경쟁 병원 비교까지.<br />우리 병원의 시그널을 읽는 다섯 단계입니다.</p></div></section>
    <div className="grid gap-8 py-8 lg:grid-cols-[230px_1fr] lg:gap-16 lg:py-14"><nav className="flex gap-2 overflow-x-auto pb-2 lg:sticky lg:top-8 lg:block lg:self-start" aria-label="가이드 목차">{sections.map(s => <a key={s.id} href={`#${s.id}`} className="flex shrink-0 items-center gap-3 border border-[#d4d6cb] px-3 py-3 text-xs text-[#687253] hover:bg-[#ff5d2a] lg:border-x-0 lg:border-t-0 lg:px-0 lg:py-5"><span className="font-mono text-[10px]">{s.number}</span>{s.id === 'profile' ? '병원 소개' : s.id === 'questions' ? '핵심 질문' : s.id === 'answers' ? 'AI 답변' : s.id === 'competitors' ? '경쟁 병원' : '변화 추적'}</a>)}</nav><div>{sections.map(s => <section id={s.id} key={s.id} className="scroll-mt-8 border-b border-[#d4d6cb] pb-12 pt-10 first:pt-0 lg:pb-16 lg:pt-14"><div className="mb-6 flex items-center gap-4"><span className="flex h-11 w-11 items-center justify-center bg-[#ff5d2a] font-mono text-sm">{s.number}</span><p className="text-[10px] font-semibold tracking-[0.14em] text-[#72756a]">{s.sub}</p></div><h2 className="text-2xl font-semibold tracking-[-0.045em] sm:text-3xl">{s.title}</h2><p className="mt-5 max-w-2xl text-sm leading-8 text-[#687253]">{s.text}</p><ul className="my-7 space-y-3 border-l-2 border-[#ff5d2a] pl-5">{s.points.map(point => <li key={point} className="flex gap-2 text-xs leading-6 text-[#687253]"><Check className="mt-1 h-3.5 w-3.5 shrink-0 text-[#44551d]" />{point}</li>)}</ul><Link href={loggedIn ? s.href : '/login'} className="inline-flex items-center gap-4 border-b border-[#141512] pb-2 text-xs font-semibold">{s.link}<ArrowUpRight className="h-4 w-4" /></Link></section>)}</div></div>
    <section className="mb-16 grid gap-8 bg-[#141512] p-7 text-white sm:p-10 lg:grid-cols-2"><div><p className="text-[10px] tracking-[0.15em] text-[#ff5d2a]">NEED A LITTLE MORE?</p><h2 className="mt-4 text-2xl font-medium tracking-[-0.04em]">궁금한 점이 남아 있나요?</h2><a href="mailto:support@patientsignal.kr" className="mt-5 inline-flex items-center gap-3 text-sm text-[#ff5d2a]">support@patientsignal.kr<ArrowUpRight className="h-4 w-4" /></a></div><div className="space-y-5">{[['어떤 플랫폼을 지원하나요?', 'ChatGPT, Claude, Gemini, Perplexity, Grok, CLOVA X, 네이버 AI 브리핑을 지원합니다. 플랜에 따라 제공 범위가 다릅니다.'], ['데이터가 아직 보이지 않아요.', '병원 정보와 추적 질문을 등록했는지 확인해 주세요. 측정이 완료되면 답변과 분석 결과가 표시됩니다.']].map(([q,a]) => <details key={q} className="group border-b border-white/20 pb-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 text-sm font-medium">{q}<Plus className="h-4 w-4 shrink-0 group-open:rotate-45" /></summary><p className="mt-4 text-xs leading-7 text-white/60">{a}</p></details>)}</div></section>
  </main><SiteFooter /></div>;
}
